version: '3'
services:
  postgres:
    restart: always
    image: "postgres:10.4-alpine"
    environment:
      POSTGRES_DB: fraud-rules-engine
      POSTGRES_USER: fraud-rules-engine
      POSTGRES_PASSWORD: fraud-rules-engine
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: "redis:3-alpine3.8"
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data