version: '3'
services:
  test:
    image: openjdk:11.0-jdk-slim
    environment:
      NEXUS_USERNAME_REPOSITORY: ${NEXUS_USERNAME}
      NEXUS_PASSWORD_REPOSITORY: ${NEXUS_PASSWORD}
      NEXUS_URL_REPOSITORY: ${NEXUS_URL}
    volumes:
      - ${MY_WORKSPACE}:/ws
    working_dir: /ws${WORKSPACE_PATH:-/}
    user: ${MY_USER:-root}
    depends_on:
      - postgres
      - redis
      - mongodb
    command: >
      ./gradlew --no-daemon -g ./.gradle-cache jacocoTestReport
  postgres:
    restart: always
    image: "postgres:10.4-alpine"
    environment:
      POSTGRES_DB: ruleflow
      POSTGRES_USER: ruleflow
      POSTGRES_PASSWORD: ruleflow
  redis:
    restart: always
    image: "redis:3-alpine3.8"
    volumes:
      - ../data/redis:/data
  mongodb:
    image: 'bitnami/mongodb:4.2.8'
    environment:
      - MONGODB_USERNAME=fraud_rules_engine
      - MONGODB_PASSWORD=fraud_rules_engine
      - MONGODB_DATABASE=fraud_rules_engine
      - MONGODB_PORT_NUMBER=27018