# Environment samples to help you build your compose:

# WORKSPACE_PATH=/devops-test_feature_cicd
# MY_WORKSPACE=/home/ec2-user/workspace
# NEXUS_URL=http://repo.ops.rappi.com

version: '3'
services:
  test:
    build: .
    volumes:
    - ${MY_WORKSPACE}:/ws
    working_dir: /ws${WORKSPACE_PATH:-/}
    user: ${MY_USER:-root}
    environment:
      NEXUS_USERNAME: ${NEXUS_USERNAME}
      NEXUS_PASSWORD: ${NEXUS_PASSWORD}
      NEXUS_URL: ${NEXUS_URL}
    command: echo "your tests runner here"
