settings:
  APP_RESPONSE_TIMEOUT: 1500
  ADDED_REQUEST_AUTH_TOKEN: "8FAC54A0EE1203E6B81833875F8D6064E65C249796ACD13B05BC8D49A65495DA"
database:
  DB_URL: "jdbc:postgresql://postgres:5432/fraud-rules-engine"
  DB_USER: "fraud-rules-engine"
  DB_PASSWORD: "fraud-rules-engine"
  DRIVER_CLASS: "org.postgresql.Driver"
  PROVIDER_CLASS: "io.vertx.ext.jdbc.spi.impl.HikariCPDataSourceProvider"
  CONNECTION_TIMEOUT: "5000"
  MAX_POOL_SIZE: "50"
  LEAK_THRESHOLD: "30000"
  MAX_LIFETIME: "280000"
  MINIMUM_IDLE: "1"
  IDLE_TIMEOUT: "60000"
redis:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
documentdb:
  CONNECTION_STRING_WRITE: "mongodb://fraud_rules_engine:fraud_rules_engine@mongodb:27018/fraud_rules_engine?replicaSet=rs0"
  MAX_CONNECTION_POOL: "10"
  CONNECT_TIMEOUT: "5000"
  LIMIT_HISTORY_MONTHS: 6
  COLLECTIONS:
    REQUEST_DATA: "request_data"