features: [
  "rp_receiver",
  "rp_payer",
  "rp_payer_receiver",
  "rp_fingerprint",
  "rp_device",
  "rp_payer_as_receiver",
  "rp_device_payer",
  "rp_device_distinct_payer",
  "rp_fingerprint_distinct_payer",
  "rp_payer_fingerprint",
  "crosses_user_fingerprint",
  "crosses_add_card_events_used_fingerprint",
  "crosses_add_card_events_other_fingerprint",
  "mk_payer",
  "mk_payer_fingerprint",
  "user_events",
  "user_by_device_events",
  "mk_user",
  "mk_device",
  "mk_device_address",
  "mk_device_storetype",
  "mk_payer_device",
  "mk_payer_address",
  "mk_payer_storetype",
  "mk_fingerprint",
  "mk_fingerprint_device",
  "mk_fingerprint_address",
  "mk_fingerprint_storetype",
  "mk_google_pay_fingerprint",
  "coupon_abuse_vector",
  "normalized_email_events",
  "mk_payer_store",
  "mk_payer_fingerprint_device",
  "mk_tickets",
  "mk_allies_store",
  "mk_geohash",
  "mk_order",
  "mk_safe_device",
  "mk_geohash_7",
  "mk_payer_fingerprint",
  "rms_payer",
  "rms_collector",
  "rms_payer_collector",
  "rp_prepaid_payer",
  "rp_payer_as_receiver",
  "rp_withdrawal_bank_account",
  "rp_withdrawal_user",
  "mk_safe_fingerprint",
  "rp_safe_device",
  "rp_safe_fingerprint",
  "mk_geohash_7",
  "rp_bp_user",
  "rp_bp_user_service",
  "interbank_rp_payer",
  "interbank_rp_receiver",
  "fake_users_user_agent",
  "fake_users_email",
  "fake_users_user",
  "crosses_registration_device",
  "crosses_login_device",
  "crosses_registration_phone_number_qty_users",
  "crosses_login_phone_number_qty_users",
  "crosses_normalized_phone_number_qty_users",
  "mk_allies_store",
  "mk_payer_address",
  "mk_payer_store",
  "mk_device_address",
  "mk_device_storetype",
  "mk_google_pay_fingerprint",
  "mk_tickets",
  "mk_allies_store",
  "mk_geohash_7",
  "coupon_abuse_vector",
  "mk_geohash"
]