settings:
  APP_RESPONSE_TIMEOUT: 1500
database:
  DB_URL: "jdbc:postgresql://postgres:5432/fraud-rules-engine"
  DB_USER: "fraud-rules-engine"
  DB_PASSWORD: "fraud-rules-engine"
  DRIVER_CLASS: "org.postgresql.Driver"
  PROVIDER_CLASS: "io.vertx.ext.jdbc.spi.impl.HikariCPDataSourceProvider"
  CONNECTION_TIMEOUT: "5000"
  MAX_POOL_SIZE: "50"
  LEAK_THRESHOLD: "30000"
  MAX_LIFETIME: "280000"
  MINIMUM_IDLE: "1"
  IDLE_TIMEOUT: "60000"
redis:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"