database:
  DB_URL: "jdbc:postgresql://localhost:5432/fraud-rules-engine"
  DB_USER: "fraud-rules-engine"
  DB_PASSWORD: "fraud-rules-engine"
  DRIVER_CLASS: "org.postgresql.Driver"
redis:
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"